# -*- coding: utf-8 -*-
"""dsm.py — DSM v1（Delta Session Mesh）SMSocket 侧编解码器（服务端）。

真源：Downloads/OpenAI兼容格式评测_20261005/DSM_v1/{规范_DSM_v1.md,dsm.schema.json}
契约：DSM_wiring_contract.md §1-§6（端点/键名/开关语义/验收矩阵），逐条遵守、不自创。
§3 硬要求：本文件的共享算法（ROLE/RID、POLICY_KEYS、CORE、validate、fingerprint、
canon_mem/canon_cons、budget_map、to_openai/to_anthropic/to_responses、split_fan、
leak_check、name_collision、encode_turn/decode_turn、decode_to_openai_shape、
merge_stream）与 SMS 侧 skill_manage_system/skill/scripts/dsm.py 逐字节同构——
由 tools/gen_server_dsm.py 从客户端文件机械抽取拼装，不手抄、不重发明；客户端一旦
改名/改语义，生成器直接 ABORT，两侧不可能悄悄漂移。
服务端差异只在三处：
  · frag/canon_mem —— 链库在 SMS 本机，服务端读不到：恒 None 并计 mem_unsupported，
    绝不静默当成「没有记忆」；
  · SchemaStore —— 服务端才是引用真源，落 <data>/runtime/dsm_schemas.json（原子写）；
  · SessionStore + encode_response —— 服务端持有会话态（d 只带新增轮次）并产出三分账
    响应信封（in/out_reason/out_answer/cache_read/cache_write/cost）。
默认全关：settings.dsm.enabled=false 时本模块不被任何路由调用，行为与今天逐字节相同（验收 A）。
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import threading
import time
from collections import OrderedDict
from pathlib import Path

log = logging.getLogger("smssocket.dsm")

# ---- server-side constants the shared codec references (see module docstring) ----
# 链在服务端不存在（链库在 SMS 本机），故 ISO 过滤集为空：_same_session 因此恒真，
# 而 frag() 恒返回 None —— 服务端 mem 一律解析不到，由 mem_unsupported 计数暴露。
ISO_CHAINS: tuple = ()
RESPONSES_STYLE = "openai-responses"      # 与 SMSocket/upstream.py 同值（出口 style 分派）
LANE_CORE_TOOLS = ("exec", "read", "write", "grep", "glob", "ls")

_mem_unsupported = 0


def frag(fid, sms=None):
    """服务端不读链：恒 None（canon_mem 因此把 id 记进 skipped）。"""
    global _mem_unsupported
    if fid:
        _mem_unsupported += 1
    return None


def mem_unsupported():
    return _mem_unsupported


_DATA_DIR = os.environ.get("SMSOCKET_DATA") or os.path.dirname(os.path.abspath(__file__))


def sms_home():
    """服务端 runtime 根（SchemaStore/SessionStore 落盘处·可经 SMSOCKET_DATA 改）。"""
    return _DATA_DIR


class _AtomicIO:
    """最小原子 JSON 读写（服务端无 SMS 的 atomic_io 模块·语义一致：临时文件 + os.replace）。"""

    @staticmethod
    def rjson(path, default=None):
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return default

    @staticmethod
    def wjson(path, doc):
        d = os.path.dirname(os.path.abspath(path))
        os.makedirs(d, exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=1)
        os.replace(tmp, path)
        return True


atomic_io = _AtomicIO()

# ===== contract §3 shared codec — extracted verbatim from the SMS client file =====
# (generated by tools/gen_server_dsm.py; do not hand-edit these bodies, edit the
#  client copy and regenerate — that is what keeps both sides byte-identical.)
ROLE = ["system", "user", "assistant", "tool", "constraint", "note"]

RID = {n: i for i, n in enumerate(ROLE)}

POLICY_KEYS = {"sid", "cid", "lane", "dep", "lat", "fan", "bill", "verify", "out", "x"}

CORE = {"v", "sch", "mem", "d", "cons", "budget"} | POLICY_KEYS

CTYPE = "application/dsm+json"

CTYPE_STREAM = "application/x-ndjson"

ENDPOINT = "/v1/dsm/chat"

ENDPOINT_SCHEMA = "/v1/dsm/schema"

REASON_TIER = {"low": 0, "mid": 1024, "high": 4096, "auto": None}

_REF_RE = re.compile(r"^sha1:[0-9a-f]{12}$")

_ID_RE = re.compile(r"^[0-9a-f]{10}$")

assert len(set(ROLE)) == len(ROLE) == len(RID), "DSM: ROLE 枚举重复"

assert [ROLE[RID[n]] for n in ROLE] == ROLE, "DSM: ROLE/RID 双射破裂（位置化即失效）"


class Unsupported(Exception):
    """信封装不下的语义（多模态 content 数组等）——调用方据此走 legacy 并打日志，
    绝不静默丢内容（契约 C：语义保真优先于强行套信封）。"""


def fingerprint(system, tools):
    """sch＝sha1(json.dumps({"s":system,"t":tools}, sort_keys, ensure_ascii=False))[:12]。
    顺序锁死是位置化的前提：工具开关变→子集变→指纹变→引用自动失效，不串味。"""
    blob = json.dumps({"s": system or "", "t": tools or []}, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return "sha1:" + hashlib.sha1(blob).hexdigest()[:12]


def _same_session(f, sid):
    """会话隔离（红线 17）：ISO 链碎片必须带 member→本 sess 边才准物化；
    非 ISO 链（user/memory/logic/knowledge…）属跨会话共享记忆，不过滤（与 prompt_pack 口径一致）。"""
    if not sid or f.get("chain") not in ISO_CHAINS:
        return True
    for e in (f.get("edges") or []):
        if len(e) >= 2 and e[1] == "member" and e[0] == sid:
            return True
    return False


def canon_mem(ids, sid=None, strict=False):
    """物化 mem：按 id 字典序（不是按得分）——顺序确定才有字节稳定前缀，才谈得上缓存命中。
    带 `+N` 后缀的引用剥掉深度位（邻居展开未落地→宁少带不误带）；跨会话 id 默认拒解并计数。"""
    out, skipped = [], []
    for raw in sorted(set((i or "").split("+")[0] for i in (ids or []) if i)):
        f = frag(raw)
        if not f:
            skipped.append(raw); continue
        if not _same_session(f, sid):
            skipped.append(raw + "!xsess"); continue
        out.append("[%s·f%d·%s] %s" % (f["id"], int(f.get("freq", 1) or 1), f["chain"], f["text"]))
    if strict and skipped:
        raise Unsupported("mem 引用不可解析/跨会话：%s" % ",".join(skipped[:4]))
    return "\n".join(out)


def canon_cons(cons):
    """约束槽位→确定性自然语言（提供商没有槽位，只能模板化，模板本身锁死以保证可复现）。"""
    if not cons:
        return ""
    L = []
    if cons.get("dedup_key"):
        L.append("去重口径：按业务键 " + "+".join(cons["dedup_key"]) + " 判重（不是按行号/整行）。")
    if cons.get("fx"):
        L.append("汇率（固定，勿自行取值）：" + "，".join("%s=%s" % (k, v) for k, v in sorted(cons["fx"].items())) + "。")
    if cons.get("round"):
        L.append("数值舍入：%s，先算后舍。" % cons["round"])
    if cons.get("output"):
        L.append("输出结构：严格按 schema %s 的位置序，不多不少。" % cons["output"])
    for c in cons.get("must", []):
        L.append("硬约束：" + c)
    return "\n".join(L)


def budget_map(b, style):
    """思考预算→各提供商真实字段（唯一能撬动 62-67% 输出侧成本的把手）。"""
    b = b or {}
    tier, mo = b.get("reason", "auto"), b.get("max_out")
    if style in ("openai", "openai-chat", "openai-responses"):
        # 与 dsm_egress.py 参考实现逐字一致（规范 §7 表格写 openai-responses→reasoning.effort，
        # 与参考实现不符——按契约「复用其算法」取参考实现，分歧已登记进交付报告）。
        out = {}
        if tier and tier != "auto":
            out["reasoning_effort"] = tier          # 分档，不动 max_tokens
        if mo:
            out["max_completion_tokens" if style == "openai-responses" else "max_tokens"] = mo
        return out
    if style == "anthropic":
        out = {}
        if tier and tier != "auto":
            out["thinking"] = {"type": "enabled", "budget_tokens": REASON_TIER[tier] or 1024}
        if mo:
            out["max_tokens"] = mo + int(out.get("thinking", {}).get("budget_tokens", 0))
        return out
    return {}


class SchemaStore:
    """同 hash 同内容：客户端持镜像只为 x.mem_off 调试与本地物化，真源在服务端 runtime。
    落盘＝<SMS_HOME>/runtime/dsm_schemas.json（atomic_io 原子替换·缓存文件不进 skill 目录）。"""

    def __init__(self, path=None, sms=None):
        self.path = path or os.path.join(sms or sms_home(), "runtime", "dsm_schemas.json")
        self.by_hash = {}
        self._loaded = False

    def _load(self):
        if self._loaded:
            return self.by_hash
        self._loaded = True
        try:
            doc = atomic_io.rjson(self.path, default={}) or {}
            self.by_hash = dict(doc.get("schemas") or {})
        except Exception:
            self.by_hash = {}
        return self.by_hash

    def _save(self):
        try:
            atomic_io.wjson(self.path, {"ts": time.strftime("%Y-%m-%dT%H:%M:%S"),
                                        "schemas": self.by_hash})
            return True
        except Exception:
            return False

    def put(self, system, tools):
        blob = json.dumps({"s": system, "t": tools}, ensure_ascii=False, sort_keys=True)
        h = "sha1:" + hashlib.sha1(blob.encode("utf-8")).hexdigest()[:12]
        self._load()[h] = {"system": system, "tools": tools, "bytes": len(blob.encode("utf-8"))}
        self._save()
        return h

    def get(self, h):
        return self._load().get(h)

    def has(self, h):
        return h in self._load()

    def refs(self):
        return len(self._load())


def validate(env):
    """回问题列表（空＝合法）。additionalProperties:false 是硬约束：新语义一律走 x.<域>.<名>。"""
    e = []
    if not isinstance(env, dict):
        return ["env 必须是对象"]
    for k in ("v", "sch", "d"):
        if k not in env:
            e.append("缺必填键 %s" % k)
    for k in env:
        if k not in CORE:
            e.append("未知顶层键 %s（封闭表 additionalProperties:false）" % k)
    if env.get("v") != 1:
        e.append("v 必须为 1（协商位）")
    sch = env.get("sch")
    if not (isinstance(sch, str) and _REF_RE.match(sch)):
        e.append("sch 格式必须 sha1:<12hex>")
    d = env.get("d")
    if not isinstance(d, list):
        e.append("d 必须是数组")
    else:
        for i, t in enumerate(d):
            if not (isinstance(t, (list, tuple)) and len(t) == 2):
                e.append("d[%d] 必须是 [role_id, text] 位置化二元" % i); continue
            if not (isinstance(t[0], int) and 0 <= t[0] <= len(ROLE) - 1):
                e.append("d[%d] role_id 越界（0-%d）" % (i, len(ROLE) - 1))
            if not isinstance(t[1], str):
                e.append("d[%d] text 必须是字符串" % i)
    mem = env.get("mem")
    if mem is not None:
        if not isinstance(mem, list):
            e.append("mem 必须是 id 数组")
        else:
            for i, x in enumerate(mem):
                if not (isinstance(x, str) and _ID_RE.match(x.split("+")[0])):
                    e.append("mem[%d] 必须是 10 位十六进制碎片 id（可带 +N 深度后缀）" % i)
    if env.get("out") is not None and env["out"] not in ("json", "delta", "msgpack"):
        e.append("out 必须 ∈ json|delta|msgpack")
    b = env.get("budget")
    if b is not None:
        if not isinstance(b, dict):
            e.append("budget 必须是对象")
        else:
            if b.get("reason") not in (None, "low", "mid", "high", "auto"):
                e.append("budget.reason 必须 ∈ low|mid|high|auto")
            for k in b:
                if k not in ("reason", "max_out", "when_exceeded"):
                    e.append("budget 未知键 %s" % k)
            if b.get("when_exceeded") not in (None, "answer_partial", "truncate", "retry_higher", "fallback_lane"):
                e.append("budget.when_exceeded 非法")
    for k, allow in (("cons", dict), ("lat", dict), ("fan", dict), ("bill", dict), ("verify", list), ("x", dict)):
        v = env.get(k)
        if v is not None and not isinstance(v, allow):
            e.append("%s 类型应为 %s" % (k, allow.__name__))
    lat = env.get("lat")
    if isinstance(lat, dict) and lat.get("on_exceed") not in (None, "failover", "degrade", "abort"):
        e.append("lat.on_exceed 非法")
    fan = env.get("fan")
    if isinstance(fan, dict):
        if not (isinstance(fan.get("n", 1), int) and 1 <= fan.get("n", 1) <= 256):
            e.append("fan.n 必须 1..256")
        if fan.get("merge") not in (None, "concat", "vote", "reduce", "first_ok"):
            e.append("fan.merge 非法")
    return e


_TURN_ROLES = (2, 3)          # assistant / tool 可能带协议外结构（tool_calls·tool_call_id）


def encode_turn(m):
    """OpenAI message → [role_id, text]。带 tool_calls 的 assistant 与带 tool_call_id 的 tool，
    把整条 turn 规范化成 JSON 字符串放进位置化 text 槽——text 属「内容面」不是协议面，
    故不违反 POLICY_KEYS 不出网；由 x.sms.turn_json=1 声明语义，decode_turn 精确还原。"""
    r = m.get("role")
    if r not in RID:
        raise Unsupported("信封无此 role：%s" % r)
    c = m.get("content")
    if isinstance(c, list):
        raise Unsupported("多模态/分段 content 不入信封（d.text 只承载字符串）")
    rid = RID[r]
    if rid in _TURN_ROLES and (m.get("tool_calls") or m.get("tool_call_id")):
        keep = {"role": r, "content": c if c is not None else ""}
        if m.get("tool_calls"):
            keep["tool_calls"] = m["tool_calls"]
        if m.get("tool_call_id"):
            keep["tool_call_id"] = m["tool_call_id"]
        return rid, json.dumps(keep, ensure_ascii=False, sort_keys=True)
    return rid, (c or "")


def decode_turn(rid, text):
    """[role_id, text] → OpenAI message（encode_turn 的逆·唯一还原规则）。"""
    m = {"role": ROLE[rid] if isinstance(rid, int) and 0 <= rid < len(ROLE) else str(rid), "content": text}
    if isinstance(rid, int) and rid in _TURN_ROLES and isinstance(text, str) and text[:1] == "{":
        try:
            j = json.loads(text)
        except Exception:
            return m
        if isinstance(j, dict) and ("tool_calls" in j or "tool_call_id" in j):
            out = {"role": j.get("role") or m["role"], "content": j.get("content", "")}
            if j.get("tool_calls"):
                out["tool_calls"] = j["tool_calls"]
            if j.get("tool_call_id"):
                out["tool_call_id"] = j["tool_call_id"]
            return out
    return m


def _turn_of(t):
    if isinstance(t, (list, tuple)):
        return (t[0] if isinstance(t[0], int) else RID.get(str(t[0]), 1)), (t[1] if len(t) > 1 else "")
    return RID.get(t.get("role"), 1), (t.get("text") or t.get("content") or "")


def _inline(env, store):
    """x.sms.inline_schema＝schema_ref 关闭位：不查仓库，直接用信封内联的 system+tools。"""
    inl = ((env.get("x") or {}).get("sms.inline_schema")) or {}
    if inl:
        return {"system": inl.get("system") or "", "tools": inl.get("tools") or []}
    return store.get(env.get("sch")) or {"system": "", "tools": []}


def to_openai(env, store, alias=None):
    rec = _inline(env, store)
    mem = "" if (env.get("x") or {}).get("mem_off") else canon_mem(env.get("mem"), env.get("sid"))
    cons = canon_cons(env.get("cons"))
    msgs = [{"role": "system", "content": rec["system"]}]
    tail = "\n".join(x for x in (mem, cons) if x)
    if tail:
        msgs.append({"role": "system", "content": tail})
    for t in env.get("d", []):
        rid, txt = _turn_of(t)
        msgs.append(decode_turn(rid, txt))
    body = {"model": alias or (env.get("x") or {}).get("sms.model") or "auto", "messages": msgs}
    if rec["tools"]:
        body["tools"] = rec["tools"]
    body.update(budget_map(env.get("budget"), "openai"))
    return body


def to_responses(env, store, alias=None):
    rec = _inline(env, store)
    mem = "" if (env.get("x") or {}).get("mem_off") else canon_mem(env.get("mem"), env.get("sid"))
    cons = canon_cons(env.get("cons"))
    inp = []
    for t in env.get("d", []):
        rid, txt = _turn_of(t)
        m = decode_turn(rid, txt)
        inp.append({"role": m["role"], "content": m.get("content") or ""})
    ins = "\n".join(x for x in (rec["system"], mem, cons) if x)
    body = {"model": alias or (env.get("x") or {}).get("sms.model") or "auto", "input": inp}
    if ins:
        body["instructions"] = ins
    if rec["tools"]:
        body["tools"] = rec["tools"]
    body.update(budget_map(env.get("budget"), "openai-responses"))
    return body


def to_anthropic(env, store, alias=None):
    rec = _inline(env, store)
    mem, cons = canon_mem(env.get("mem"), env.get("sid")), canon_cons(env.get("cons"))
    sys_txt = "\n".join(x for x in (rec["system"], mem, cons) if x)
    msgs = []
    for t in env.get("d", []):
        rid, txt = _turn_of(t)
        role = "assistant" if rid == 2 else "user"
        if msgs and msgs[-1]["role"] == role:
            msgs[-1]["content"][0]["text"] += "\n" + txt        # 同角色合并（提供商要求交替）
        else:
            msgs.append({"role": role, "content": [{"type": "text", "text": txt}]})
    body = {"model": alias or (env.get("x") or {}).get("sms.model") or "auto",
            "system": sys_txt, "messages": msgs}
    if rec["tools"]:
        body["tools"] = [{"name": f["function"]["name"], "description": f["function"].get("description", ""),
                          "input_schema": f["function"].get("parameters", {})} for f in rec["tools"]]
    body.update(budget_map(env.get("budget"), "anthropic"))
    return body


def split_fan(env, done_lanes=None):
    """fan 是声明不是线程：一条内部报文 → N 个 lane 子报文 → 网关 /v1/batch 的 requests[]。
    dep 未满足的道不进批（串行）；同 sid/sch 共享会话态与 schema 引用。
    兼容参考实现的 env["_done_lanes"] 写法（done_lanes=None 时回退读它）。"""
    fan = env.get("fan") or {}
    n = int(fan.get("n", 1) or 1)
    lanes = fan.get("lane_ids") or ["%s.%d" % (env.get("lane", "l"), i) for i in range(n)]
    done = set(done_lanes if done_lanes is not None else (env.get("_done_lanes") or []))
    items, ready = [], []
    for lid in lanes:
        sub = {k: v for k, v in env.items() if k not in ("fan", "_done_lanes")}
        sub["lane"] = lid
        d = (fan.get("per_lane") or {}).get(lid)
        if d:
            sub["d"] = d
        items.append(sub)
        blocked = [x for x in (env.get("dep") or []) if x not in done]
        (ready if not blocked else []).append(lid)
    return {"requests": items, "dispatchable": bool(ready),
            "concurrency": int(fan.get("concurrency", len(ready) or 1)),
            "ready": ready, "blocked": [l for l in lanes if l not in ready],
            "merge": fan.get("merge", "concat"), "fail_fast": bool(fan.get("fail_fast", False))}


def leak_check(env, body):
    """红线一：内部策略键不得作为出网报文的「顶层键」出现（顶层＝协议面，嵌套＝内容面）。"""
    return sorted(k for k in POLICY_KEYS if k != "out" and k in (body or {}))


def name_collision(store, sch):
    """红线二登记：内部短键与工具参数名撞车（实测本机 task.lane / task_plan.lane 已撞）。
    新增核心键前必须先跑它。tools schema 属内容面，允许存在但必须登记。"""
    rec = store.get(sch) or {"tools": []}
    names = set()
    for t in rec.get("tools") or []:
        props = ((t.get("function") or {}).get("parameters") or {}).get("properties") or {}
        names |= set(props)
    return sorted(names & (CORE | {"model"}))


def _norm_tool_call(i, tc):
    f = (tc.get("function") or {}) if isinstance(tc, dict) else {}
    name = f.get("name") or tc.get("name") or tc.get("tool") or ""
    args = f.get("arguments")
    if args is None:
        args = tc.get("arguments") if tc.get("arguments") is not None else tc.get("parameters")
    if isinstance(args, (dict, list)):
        args = json.dumps(args, ensure_ascii=False, sort_keys=True)
    return {"id": tc.get("id") or ("dsm_tc_%d" % i), "type": "function",
            "function": {"name": str(name), "arguments": args if isinstance(args, str) else "{}"}}


def decode_to_openai_shape(resp):
    """DSM 响应信封 → {"model","choices":[{"message","finish_reason"}],"usage"}。
    answer＝字符串 或 [{tool_call}]；stop 一律映射进 OpenAI 词表（end_turn→stop /
    tool_call→tool_calls / length→length），未知值落 stop，原始 stop 留在返回的
    dsm 段——按 finish_reason 分支的调用方绝不因走 DSM 而改变行为。
    usage 三分账回填 OpenAI 口径：in→prompt_tokens，out_reason+out_answer→completion_tokens，
    cache_read→prompt_tokens_details.cached_tokens，out_reason→completion_tokens_details.reasoning_tokens。"""
    if isinstance(resp, list):                       # out=delta 的原始行也收（幂等归并）
        resp = merge_stream(resp)
    r = resp or {}
    ans = r.get("answer")
    tcs, parts = [], []
    if isinstance(ans, str):
        parts.append(ans)
    elif isinstance(ans, list):
        for i, it in enumerate(ans):
            if isinstance(it, dict) and (it.get("function") or it.get("name") or it.get("tool")):
                tcs.append(_norm_tool_call(i, it))
            elif isinstance(it, str):
                parts.append(it)
            else:
                parts.append(json.dumps(it, ensure_ascii=False, default=str))
    content = "\n".join(p for p in parts if p != "")
    reason = r.get("reason") or {}
    if isinstance(reason, str):
        reason = {"summary": reason}
    u = r.get("usage") or {}
    fin = str(r.get("stop") or "")
    # stop→finish_reason 必须落在 OpenAI 词表内（契约 §4）。把 DSM 的 end_turn 直接抄进
    # finish_reason，任何按 OpenAI 口径分支的调用方都会把它当「未知停止原因」，DSM 路径
    # 与 legacy 路径就此分叉——「工具循环零改动」的承诺也就破了。
    _S2F = {"end_turn": "stop", "stop": "stop", "tool_call": "tool_calls",
            "length": "length", "max_tokens": "length",
            "content_filter": "content_filter"}
    finish = "tool_calls" if tcs else _S2F.get(fin, "stop")
    inp = int(u.get("in") or 0); orz = int(u.get("out_reason") or 0); oa = int(u.get("out_answer") or 0)
    usage = {"prompt_tokens": inp, "completion_tokens": orz + oa, "total_tokens": inp + orz + oa,
             "prompt_tokens_details": {"cached_tokens": int(u.get("cache_read") or 0)},
             "completion_tokens_details": {"reasoning_tokens": orz}}
    if u.get("cost") is not None:
        usage["cost"] = u.get("cost"); usage["currency"] = u.get("currency")
    usage["dsm"] = u                                    # 三分账原样留存（归因用·不覆盖 OpenAI 口径）
    msg = {"role": "assistant", "content": content.replace("\x00", "").replace("\r", "\n"),
           "reasoning_content": reason.get("summary") or ""}
    if tcs:
        msg["tool_calls"] = tcs
    return {"model": r.get("model") or r.get("egress") or "dsm", "object": "chat.completion",
            "choices": [{"index": 0, "message": msg, "finish_reason": finish}], "usage": usage,
            "dsm": {"v": r.get("v"), "sid": r.get("sid"), "lane": r.get("lane"), "seq": r.get("seq"),
                    "egress": r.get("egress"), "lanes": r.get("lanes"),
                    "stop": fin}}


def merge_stream(envs):
    """out=delta：服务端按 seq 吐 ndjson 信封，本侧归并成一条完整响应信封再解码。
    文本增量按 seq 拼接；reason/usage/stop 取最后一个非空值（乱序到达也稳定）。"""
    seqs = sorted((e for e in (envs or []) if isinstance(e, dict)), key=lambda e: int(e.get("seq") or 0))
    out = {"v": 1, "answer": "", "reason": {"tokens": 0, "summary": ""}}
    for e in seqs:
        for k in ("sid", "lane", "egress", "stop", "model"):
            if e.get(k):
                out[k] = e[k]
        a = e.get("answer")
        if isinstance(a, list):
            # 收口帧的 tool_calls 数组**必须胜出**：服务端正文按 seq 先吐完，末帧才带
            # 工具调用；旧写法「非空字符串时丢弃数组」＝ delta 模式下工具循环整条断掉
            # （2026-10-06 实测）。文本与工具调用同时存在时按契约 §4 只保留数组，与
            # json 模式（encode_response 同规则）保持同形。
            out["answer"] = a if a else out["answer"]
        elif isinstance(a, str) and a:
            out["answer"] = (out["answer"] if isinstance(out["answer"], str) else "") + a
        rs = e.get("reason") or {}
        if isinstance(rs, str):
            out["reason"]["summary"] += rs
        else:
            out["reason"]["summary"] += rs.get("summary") or ""
            out["reason"]["tokens"] = int(rs.get("tokens") or out["reason"]["tokens"])
        if e.get("usage"):
            out["usage"] = e["usage"]
        if e.get("lanes"):
            out["lanes"] = e["lanes"]
    return out


# ===== server-only: 会话态（delta 累积）+ 响应信封（三分账） =====
from collections import OrderedDict

STATE_MAX_SESSIONS = 2000
STATE_TTL = 3600.0


class StateMismatch(Exception):
    """客户端水位与服务端会话态不符——绝不猜前缀（宁可让客户端降级 legacy 全量重发）。"""


def _now():
    import time
    return time.time()


class SessionStore:
    """按 sid|cid|lane|sch 累积 d（客户端只发新增轮次·契约 §3/§10）。

    判定唯一依据是客户端送来的 x.sms.delta_from（它自己 delta_window 的起始下标）：
      · == 已存条数 → 正常增量，追加；
      · == 0        → 客户端全量重同步，整表替换；
      · 其他        → 水位不符 → StateMismatch（路由回 409，客户端按 fallback 降级 legacy，
                      绝不静默少发历史——语义保真优先于省字节，与客户端 delta_window 同口径）。
    落盘＝<data>/runtime/dsm_sessions.json（重启不丢·原子写）。
    """

    def __init__(self, path=None):
        self.path = path or os.path.join(sms_home(), "runtime", "dsm_sessions.json")
        self._lock = threading.Lock()
        self._mem: "OrderedDict[str, dict]" = OrderedDict()
        self._loaded = False

    def _load(self):
        if self._loaded:
            return
        self._loaded = True
        doc = atomic_io.rjson(self.path, default={}) or {}
        cut = _now() - STATE_TTL
        for k, v in (doc.get("sessions") or {}).items():
            if isinstance(v, dict) and float(v.get("ts") or 0) > cut and isinstance(v.get("d"), list):
                self._mem[k] = v

    def key(self, env):
        x = env.get("x") or {}
        return "%s|%s|%s|%s" % (env.get("sid") or "-", env.get("cid") or "-",
                                env.get("lane") or "-", env.get("sch") or "-")

    def apply(self, env):
        """回该信封应物化的完整 d（累积后的历史）。"""
        with self._lock:
            self._load()
            k = self.key(env)
            d = list(env.get("d") or [])
            frm = (env.get("x") or {}).get("sms.delta_from")
            cur = self._mem.get(k)
            n = len(cur["d"]) if cur else 0
            if frm is None:
                # 老客户端不带水位：只能按「全量」处理（不做累积，语义无损）
                full = d
            elif int(frm) == 0:
                full = d
            elif int(frm) == n:
                full = (cur["d"] if cur else []) + d
            else:
                raise StateMismatch("delta_from=%s 但服务端已存 %d 轮（key=%s）" % (frm, n, k))
            self._mem[k] = {"d": full, "ts": _now()}
            self._mem.move_to_end(k)
            while len(self._mem) > STATE_MAX_SESSIONS:
                self._mem.popitem(last=False)
            self._save()
            return full

    def reset(self, env):
        with self._lock:
            self._mem.pop(self.key(env), None)
            self._save()

    def _save(self):
        try:
            atomic_io.wjson(self.path, {"ts": int(_now()),
                                        "sessions": {k: v for k, v in self._mem.items()}})
        except Exception as e:
            log.warning("dsm session state persist failed: %s", e)

    def count(self):
        with self._lock:
            self._load()
            return len(self._mem)


_sessions: SessionStore | None = None
_schemas: SchemaStore | None = None


def sessions():
    global _sessions
    if _sessions is None:
        _sessions = SessionStore()
    return _sessions


def schemas():
    global _schemas
    if _schemas is None:
        _schemas = SchemaStore()
    return _schemas

def _split_usage(u: dict) -> dict:
    """OpenAI usage → DSM 三分账（缺字段一律 0，绝不猜）。"""
    u = u or {}
    pin = int(u.get("prompt_tokens", 0) or 0)
    pout = int(u.get("completion_tokens", 0) or 0)
    cd = u.get("completion_tokens_details") or {}
    pd = u.get("prompt_tokens_details") or {}
    rz = int(cd.get("reasoning_tokens", u.get("reasoning_tokens", 0)) or 0)
    ans = max(0, pout - rz)
    return {"in": pin, "out_reason": rz, "out_answer": ans,
            "cache_read": int(pd.get("cached_tokens", u.get("cache_read", 0)) or 0),
            "cache_write": int(pd.get("cache_creation_input_tokens",
                                      u.get("cache_write", 0)) or 0),
            "total": int(u.get("total_tokens", pin + pout) or 0)}


def encode_response(body: dict, env: dict, alias: str = "", egress: str = "",
                    cost: dict | None = None, seq: int = 1) -> dict:
    """提供商 OpenAI 形状 → DSM 响应信封（契约 §4·decode_to_openai_shape 的逆）。

    answer：纯文本＝字符串；带 tool_calls＝[{...原始 function 结构}] 数组（客户端
    _norm_tool_call 精确还原，工具循环零改动＝验收 B 的前提）。
    usage 三分账在此产出——这是「先有度量再谈优化」的落点（规范 §8）。
    """
    ch = ((body or {}).get("choices") or [{}])[0]
    msg = ch.get("message") or {}
    tcs = msg.get("tool_calls") or []
    txt = msg.get("content") or ""
    reason = msg.get("reasoning_content") or msg.get("reasoning") or ""
    fin = str(ch.get("finish_reason") or "")
    if tcs:
        stop = "tool_call"
        answer = [tc for tc in tcs]
    elif fin == "length":
        stop, answer = "length", txt
    else:
        stop, answer = "end_turn", txt
    u = _split_usage(body.get("usage"))
    env = env or {}
    out = {"v": 1, "seq": int(seq), "stop": stop, "answer": answer, "usage": u,
           "reason": {"tokens": u["out_reason"], "summary": reason if isinstance(reason, str) else ""}}
    for k in ("sid", "lane"):
        if env.get(k):
            out[k] = env[k]
    if alias:
        out["model"] = alias
    if egress:
        out["egress"] = egress
    if cost:
        u["cost"] = cost.get("amount")
        u["currency"] = cost.get("currency")
        out["bill"] = {"display": cost.get("display"),
                       "display_currency": cost.get("display_currency")}
    return out


def materialize(env: dict, alias: str = "", style: str = "openai-chat",
                store: SchemaStore | None = None, sess: SessionStore | None = None,
                require_registered: bool = False, use_session: bool = True) -> dict:
    """信封 → 提供商指定 body（出口翻译·策略键永不入 body，leak_check 兜底）。

    require_registered=true 且引用未登记 → Unsupported（契约：宁可拒绝也不发半截 SYS）。
    use_session=False：调用方已自备完整 d —— fan 干跑/只读检视绝不推进水位，
    否则一次预览就把会话态污染成「已收到这些轮次」。
    """
    store = store or schemas()
    if require_registered and not store.has(env.get("sch")) and not (env.get("x") or {}).get("sms.inline_schema"):
        raise Unsupported("sch %s 未登记（dsm.require_registered_schema=true）" % env.get("sch"))
    full_env = dict(env)
    if use_session:
        full_env["d"] = (sess or sessions()).apply(env)
    if style in ("anthropic",):
        body = to_anthropic(full_env, store, alias)
    elif style in ("openai-responses", RESPONSES_STYLE):
        body = to_responses(full_env, store, alias)
    else:
        body = to_openai(full_env, store, alias)
    leak = leak_check(full_env, body)
    if leak:
        raise Unsupported("策略键泄漏：%s" % ",".join(leak))
    return body


def register_schema(ref: str, system: str, tools: list, store: SchemaStore | None = None) -> dict:
    """首帧登记（POST /v1/dsm/schema·幂等）。ref 必须与内容指纹一致，否则拒登。"""
    store = store or schemas()
    want = fingerprint(system, tools)
    if ref and ref != want:
        raise Unsupported("ref 与内容不符：送 %s 算得 %s" % (ref, want))
    h = store.put(system or "", tools or [])
    return {"ref": h, "bytes": (store.get(h) or {}).get("bytes", 0), "stored": store.refs()}


def schema_of(ref: str, store: SchemaStore | None = None) -> dict | None:
    return (store or schemas()).get(ref)


_settings_dsm = None


def bind_settings(dsm_cfg) -> None:
    """记住服务端开关（healthz 读它，避免每次探测都去碰 Settings）。"""
    global _settings_dsm
    _settings_dsm = dsm_cfg


def configure(schema_path=None, session_path=None, budget_map=None):
    """服务端启动/热重载接线：把 Settings.dsm 的路径与档位表落到两个 store 上。

    路径来自 dsm.schema_store（abs_path 解析），会话态与引用同目录，一行配置管
    两个文件；budget_map 覆盖 REASON_TIER（客户端默认 low=0 是「不花思考预算」，
    服务端可按提供商实际能力抬高）。
    """
    global _sessions, _schemas
    if schema_path:
        _schemas = SchemaStore(str(schema_path))
    if session_path:
        _sessions = SessionStore(str(session_path))
    if isinstance(budget_map, dict):
        for k, v in budget_map.items():
            kk = str(k).strip().lower()
            if kk in REASON_TIER:
                try:
                    REASON_TIER[kk] = max(0, int(v))
                except (TypeError, ValueError):
                    pass
    return {"schemas": str((_schemas or SchemaStore()).path),
            "sessions": str((_sessions or SessionStore()).path),
            "budget_map": dict(REASON_TIER)}


def state() -> dict:
    """可观测性（契约 §5：不看配置文件就能回答「DSM 到底开没开」）。"""
    return {"enabled": bool(_settings_dsm and _settings_dsm.enabled),
            "openai_compat": bool(not _settings_dsm or _settings_dsm.openai_compat),
            "schemas": _schemas.refs() if _schemas is not None else 0,
            "sessions": _sessions.count() if _sessions is not None else 0,
            "mem_unsupported": _mem_unsupported,
            "budget_map": dict(REASON_TIER)}
