# -*- coding: utf-8 -*-
"""Generate SMSocket/dsm.py from the SMS client codec so contract §3 (byte-identical
shared algorithms) is machine-guaranteed rather than hand-copied.

Usage: python -B gen_server_dsm.py <client_dsm.py> <out.py> <head.py> <tail.py>
Any drift in the client file aborts the build (missing name / missing marker).
"""
import ast, io, sys

CLIENT, OUT, HEADER, TAIL = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
src = io.open(CLIENT, encoding="utf-8").read()
lines = src.splitlines(keepends=True)
tree = ast.parse(src)

SEG = {}
for n in tree.body:
    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        SEG[n.name] = (n.lineno, n.end_lineno)
    elif isinstance(n, ast.Assign) and isinstance(n.targets[0], ast.Name):
        SEG.setdefault(n.targets[0].id, (n.lineno, n.end_lineno))
    elif isinstance(n, ast.Assert):
        SEG.setdefault("__assert__%d" % n.lineno, (n.lineno, n.end_lineno))


def seg(name):
    if name not in SEG:
        raise SystemExit("ABORT: client dsm.py no longer defines %s" % name)
    a, b = SEG[name]
    return "".join(lines[a - 1:b])


# constants defined server-side in the head (they touch chains/settings, absent here)
SKIP_CONST = {"ISO_CHAINS", "LANE_CORE_TOOLS", "DEFAULTS"}
CONSTS = ["ROLE", "RID", "POLICY_KEYS", "CORE", "CTYPE", "CTYPE_STREAM", "ENDPOINT",
          "ENDPOINT_SCHEMA", "REASON_TIER", "_REF_RE", "_ID_RE"]
ASSERTS = [k for k in SEG if k.startswith("__assert__")]
NAMES = ["Unsupported", "fingerprint", "_same_session", "canon_mem", "canon_cons",
         "budget_map", "SchemaStore", "validate", "_TURN_ROLES", "encode_turn",
         "decode_turn", "_turn_of", "_inline", "to_openai", "to_responses",
         "to_anthropic", "split_fan", "leak_check", "name_collision",
         "_norm_tool_call", "decode_to_openai_shape", "merge_stream"]
MARK = {"ROLE": 'ROLE = ["system", "user", "assistant", "tool", "constraint", "note"]',
        "CORE": "POLICY_KEYS", "SchemaStore": "def put(self, system, tools)",
        "to_openai": '"messages": msgs', "validate": "additionalProperties"}

for k, m in MARK.items():
    if m not in seg(k):
        raise SystemExit("ABORT: %s no longer contains %r" % (k, m))
for k in SKIP_CONST:
    if k in SEG and k in CONSTS:
        raise SystemExit("ABORT: %s must stay server-side" % k)

buf = [io.open(HEADER, encoding="utf-8").read(),
       "\n# ===== contract §3 shared codec — extracted verbatim from the SMS client file =====\n",
       "# (generated by tools/gen_server_dsm.py; do not hand-edit these bodies, edit the\n",
       "#  client copy and regenerate — that is what keeps both sides byte-identical.)\n"]
for c in CONSTS:
    buf.append(seg(c) + "\n")
for a in sorted(ASSERTS, key=lambda k: int(k.split("__")[-1])):
    buf.append(seg(a) + "\n")
buf.append("\n")
for nm in NAMES:
    buf.append(seg(nm) + "\n\n")
buf.append(io.open(TAIL, encoding="utf-8").read())
out = "".join(buf)
io.open(OUT, "w", encoding="utf-8", newline="\n").write(out)
print("generated %s: %d lines, %d consts, %d asserts, %d defs"
      % (OUT, out.count("\n") + 1, len(CONSTS), len(ASSERTS), len(NAMES)))
